name: Souqi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check repository
        run: |
          echo "Souqi Actions is working successfully!"
          echo "Repository checked successfully."
